# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import loan_pb2 as loan__pb2


class LoanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessLoanRequest = channel.unary_unary(
                '/LoanService/ProcessLoanRequest',
                request_serializer=loan__pb2.LoanRequest.SerializeToString,
                response_deserializer=loan__pb2.LoanResponse.FromString,
                )
        self.getLoanHistory = channel.unary_unary(
                '/LoanService/getLoanHistory',
                request_serializer=loan__pb2.LoansHistoryRequest.SerializeToString,
                response_deserializer=loan__pb2.LoansHistoryResponse.FromString,
                )


class LoanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessLoanRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLoanHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessLoanRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessLoanRequest,
                    request_deserializer=loan__pb2.LoanRequest.FromString,
                    response_serializer=loan__pb2.LoanResponse.SerializeToString,
            ),
            'getLoanHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.getLoanHistory,
                    request_deserializer=loan__pb2.LoansHistoryRequest.FromString,
                    response_serializer=loan__pb2.LoansHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LoanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LoanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessLoanRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LoanService/ProcessLoanRequest',
            loan__pb2.LoanRequest.SerializeToString,
            loan__pb2.LoanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getLoanHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LoanService/getLoanHistory',
            loan__pb2.LoansHistoryRequest.SerializeToString,
            loan__pb2.LoansHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
